version: "3.9"
services: 
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./volumes/cache:/data
  
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./volumes/data:/db

  rabbitmq:
    container_name: rabbitmq_container
    image: ''
    restart: always
    ports:
     #AMQP port
     - '5672:5672'
     #Dasboard port
     - '15672:15672'

